site_name: MathematicsCode Documentations
nav:
    - Home: index.md
    - \|/: null.md
    - Matrix: Matrix.md
    - \|/: null.md
    - T: T.md
    - det: det.md
theme:
      name: null
      custom_dir: 'cinder-superhero'
